# Generated by Django 5.0.4 on 2025-09-11 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management_app', '0001_initial'),
        ('user_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='categorytagsmodel',
            index=models.Index(fields=['name'], name='idx_categorytag_name'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='category_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management_app.categorytagsmodel'),
        ),
        migrations.AddField(
            model_name='favouritemodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feedbackmodel',
            index=models.Index(fields=['email'], name='management__email_5c00a3_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackmodel',
            index=models.Index(fields=['title'], name='management__title_6cecee_idx'),
        ),
        migrations.AddField(
            model_name='firmmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='helpandsupportmodel',
            index=models.Index(fields=['email'], name='management__email_413ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='helpandsupportmodel',
            index=models.Index(fields=['title'], name='management__title_472ea1_idx'),
        ),
        migrations.AddField(
            model_name='inquirymodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquirymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycdetailsmodel',
            name='business_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.businesscategorymodel'),
        ),
        migrations.AddField(
            model_name='bankdetailsmodel',
            name='kyc_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='management_app.kycdetailsmodel'),
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='parent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.locationmodel'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.locationmodel'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.rolemodel'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='user_app.rolemodel'),
        ),
        migrations.AddIndex(
            model_name='onlinepaymentoffer',
            index=models.Index(fields=['start_price_value'], name='idx_start_price_value'),
        ),
        migrations.AddIndex(
            model_name='onlinepaymentoffer',
            index=models.Index(fields=['end_price_value'], name='idx_end_price_value'),
        ),
        migrations.AddIndex(
            model_name='onlinepaymentoffer',
            index=models.Index(fields=['percentage_off'], name='idx_percentage_off'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_app.addressmodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_app.brandmodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='firm_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_app.firmmodel'),
        ),
        migrations.AddField(
            model_name='orderlinesmodel',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderrelation', to='management_app.ordermodel'),
        ),
        migrations.AddIndex(
            model_name='pagemodel',
            index=models.Index(fields=['title'], name='idx_title'),
        ),
        migrations.AddIndex(
            model_name='pagemodel',
            index=models.Index(fields=['type'], name='idx_type'),
        ),
        migrations.AddIndex(
            model_name='pagemodel',
            index=models.Index(fields=['description'], name='idx_description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_app.brandmodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='product_single_category', to='management_app.categorymodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='sub_category',
            field=models.ManyToManyField(blank=True, related_name='product_sub_category', to='management_app.categorymodel'),
        ),
        migrations.AddField(
            model_name='productimagemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='management_app.productmodel'),
        ),
        migrations.AddField(
            model_name='orderlinesmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management_app.productmodel'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.productmodel'),
        ),
        migrations.AddField(
            model_name='inquirymodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.productmodel'),
        ),
        migrations.AddField(
            model_name='favouritemodel',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.productmodel'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='management_app.productmodel'),
        ),
        migrations.AddIndex(
            model_name='producttag',
            index=models.Index(fields=['name'], name='idx_producttag_name'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_tag',
            field=models.ManyToManyField(blank=True, to='management_app.producttag'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.productmodel'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management_app.purchaseorder'),
        ),
        migrations.AddField(
            model_name='serialnumbersmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serial', to='management_app.productmodel'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='serialno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.serialnumbersmodel'),
        ),
        migrations.AddField(
            model_name='thirdpartymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='third_party_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_app.thirdpartymodel'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='management_app.vendor'),
        ),
        migrations.AddIndex(
            model_name='categorymodel',
            index=models.Index(fields=['name'], name='idx_category_name'),
        ),
        migrations.AddIndex(
            model_name='categorymodel',
            index=models.Index(fields=['image'], name='idx_category_image'),
        ),
        migrations.AddIndex(
            model_name='categorymodel',
            index=models.Index(fields=['sequence'], name='idx_category_sequence'),
        ),
        migrations.AddIndex(
            model_name='categorymodel',
            index=models.Index(fields=['is_active'], name='idx_category_is_active'),
        ),
        migrations.AddIndex(
            model_name='categorymodel',
            index=models.Index(fields=['full_pathtext'], name='idx_category_full_pathtext'),
        ),
        migrations.AddIndex(
            model_name='kycdetailsmodel',
            index=models.Index(fields=['firm_name'], name='management__firm_na_89ef16_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdetailsmodel',
            index=models.Index(fields=['business_category'], name='management__busines_6afe72_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdetailsmodel',
            index=models.Index(fields=['gstin_no'], name='management__gstin_n_b505d5_idx'),
        ),
        migrations.AddIndex(
            model_name='bankdetailsmodel',
            index=models.Index(fields=['bank_name'], name='management__bank_na_9ba6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='bankdetailsmodel',
            index=models.Index(fields=['account_number'], name='management__account_48645b_idx'),
        ),
        migrations.AddIndex(
            model_name='bankdetailsmodel',
            index=models.Index(fields=['ifsc_code'], name='management__ifsc_co_03c633_idx'),
        ),
        migrations.AddIndex(
            model_name='newsmodel',
            index=models.Index(fields=['title'], name='management__title_9952e2_idx'),
        ),
        migrations.AddIndex(
            model_name='newsmodel',
            index=models.Index(fields=['role'], name='management__role_id_331f51_idx'),
        ),
        migrations.AddIndex(
            model_name='inquirymodel',
            index=models.Index(fields=['status'], name='management__status_a506af_idx'),
        ),
        migrations.AddIndex(
            model_name='inquirymodel',
            index=models.Index(fields=['name', 'status'], name='management__name_id_62fc98_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['name'], name='idx_name'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['short_name'], name='idx_short_name'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['product_price'], name='idx_product_price'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['product_type'], name='idx_product_type'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['is_archived'], name='idx_is_archived'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['is_published'], name='idx_is_published'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['brand'], name='idx_brand'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['product_use_type'], name='idx_product_use_type'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['created_at'], name='idx_product_created_at'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['is_tracking'], name='idx_product_is_tracking'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['hsn_code'], name='idx_hsn_code'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['weight'], name='idx_weight'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['created_at'], name='idx_inventory_created_at'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product'], name='idx_inventory_product'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['location_stock'], name='idx_inventory_location'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['serialno'], name='idx_inventory_serialno'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['order_id'], name='idx_order_reference'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['order_date'], name='idx_order_date'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['final_total'], name='idx_final_total'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['is_paid'], name='idx_is_paid'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['is_expired'], name='idx_is_expired'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['is_gift'], name='idx_is_gift'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['gift_message'], name='idx_gift_message'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['applied_voucher_code'], name='idx_applied_voucher_code'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['margin'], name='idx_margin'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['is_ecommerce'], name='idx_is_ecommerce'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['note'], name='idx_note'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['source_doc'], name='idx_source_doc'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['created_at'], name='idx_order_created_at'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['order_status'], name='idx_order_status'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['delivery_date'], name='idx_delivery_date'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['expiration_date'], name='idx_expiration_date'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['pay_type'], name='idx_pay_type'),
        ),
    ]
