# Generated by Django 5.0.4 on 2025-09-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('flat', 'Flat Discount'), ('percentage', 'Percentage Discount')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinepaymentoffermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='onlinepaymentoffermodel',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinepaymentoffermodel',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
