# Generated by Django 5.0.4 on 2025-09-19 11:55

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0004_alter_ordermodel_customer'),
        ('user_app', '0003_usermodel_firm_name_alter_rolemodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos')),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gstin', models.CharField(blank=True, help_text='GST Identification Number', max_length=15, null=True, verbose_name='GSTIN')),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN')),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company', to='user_app.addressmodel')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_app.companymodel'),
        ),
        migrations.AddIndex(
            model_name='companymodel',
            index=models.Index(fields=['name'], name='idx_company_name'),
        ),
        migrations.AddIndex(
            model_name='companymodel',
            index=models.Index(fields=['code'], name='idx_company_code'),
        ),
        migrations.AddIndex(
            model_name='companymodel',
            index=models.Index(fields=['is_active'], name='idx_company_is_active'),
        ),
        migrations.AddIndex(
            model_name='companymodel',
            index=models.Index(fields=['gstin'], name='idx_company_gstin'),
        ),
        migrations.AddIndex(
            model_name='companymodel',
            index=models.Index(fields=['pan_number'], name='idx_company_pan'),
        ),
    ]
