# Generated by Django 5.0.4 on 2025-09-24 12:34

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import tinymce_4.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0006_homecategorymodel_cart_visitor_and_more'),
        ('user_app', '0004_visitormodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_status',
            field=models.CharField(choices=[('Purchase Order', 'Purchase Order'), ('RFQ', 'RFQ'), ('Cancelled', 'Cancelled')], default='RFQ', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_delivery_address', to='user_app.addressmodel', verbose_name='Delivery Address'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sub_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='serial_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_app.serialnumbersmodel'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='sub_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_app.categorytagsmodel'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='user_app.addressmodel'),
        ),
        migrations.AlterField(
            model_name='orderlinesmodel',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderrelation', to='management_app.ordermodel'),
        ),
        migrations.AlterField(
            model_name='orderlinesmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_app.productmodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.addressmodel'),
        ),
        migrations.AlterField(
            model_name='productreviewmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serialnumbersmodel',
            name='alert_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Alert Date'),
        ),
        migrations.AlterField(
            model_name='serialnumbersmodel',
            name='best_before_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Best before Date'),
        ),
        migrations.AlterField(
            model_name='serialnumbersmodel',
            name='end_of_life',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Of Life Date'),
        ),
        migrations.AlterField(
            model_name='serialnumbersmodel',
            name='removal_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removal Date'),
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('banner', models.ImageField(upload_to='Blog_Banners')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('content', tinymce_4.fields.TinyMCEModelField()),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['title'], name='idx_blog_title'), models.Index(fields=['published_at'], name='idx_blog_published_at'), models.Index(fields=['is_published'], name='idx_blog_is_published'), models.Index(fields=['banner'], name='idx_blog_banner')],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Clientreview/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='idx_client_name'), models.Index(fields=['description'], name='idx_client_description'), models.Index(fields=['created_at'], name='idx_client_created_at'), models.Index(fields=['is_active'], name='idx_client_is_active'), models.Index(fields=['image'], name='idx_client_image')],
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_type', models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], default='Individual', max_length=10)),
                ('contact_role', models.CharField(choices=[('Customer', 'Customer'), ('Vendor', 'Vendor'), ('pos_customer', 'pos_customer')], default='Customer', max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('another_phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('mail_subscription_status', models.BooleanField(default=True, help_text='This will be unchecked if user unsubscribes from all mails.', verbose_name='Mail Subscription')),
                ('gstin', models.CharField(blank=True, help_text='GST Identification Number', max_length=255, null=True, verbose_name='GSTIN')),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN')),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.addressmodel')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.countrymodel')),
                ('many_address', models.ManyToManyField(blank=True, related_name='contacts', to='user_app.addressmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='management_app.contactmodel'),
        ),
        migrations.CreateModel(
            name='OnlinePaymentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('payment_datetime', models.DateTimeField()),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_app.ordermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='contactmodel',
            index=models.Index(fields=['user'], name='idx_contact_user'),
        ),
        migrations.AddIndex(
            model_name='contactmodel',
            index=models.Index(fields=['name'], name='idx_contact_name'),
        ),
        migrations.AddIndex(
            model_name='contactmodel',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
        migrations.AddIndex(
            model_name='contactmodel',
            index=models.Index(fields=['contact_type'], name='idx_contact_type'),
        ),
        migrations.AddIndex(
            model_name='contactmodel',
            index=models.Index(fields=['contact_role'], name='idx_contact_role'),
        ),
        migrations.AddIndex(
            model_name='contactmodel',
            index=models.Index(fields=['phone_no'], name='idx_phone_no'),
        ),
        migrations.AddIndex(
            model_name='contactmodel',
            index=models.Index(fields=['email'], name='idx_email'),
        ),
        migrations.AddIndex(
            model_name='contactmodel',
            index=models.Index(fields=['gstin'], name='idx_gstin'),
        ),
        migrations.AddIndex(
            model_name='contactmodel',
            index=models.Index(fields=['pan_number'], name='idx_pan_number'),
        ),
        migrations.AddIndex(
            model_name='contactmodel',
            index=models.Index(fields=['another_phone_no'], name='idx_another_phone_no'),
        ),
        migrations.AddIndex(
            model_name='contactmodel',
            index=models.Index(fields=['is_active'], name='idx_is_active'),
        ),
        migrations.AddIndex(
            model_name='onlinepaymentsmodel',
            index=models.Index(fields=['order_id'], name='idx_order_id'),
        ),
        migrations.AddIndex(
            model_name='onlinepaymentsmodel',
            index=models.Index(fields=['user'], name='idx_user'),
        ),
        migrations.AddIndex(
            model_name='onlinepaymentsmodel',
            index=models.Index(fields=['status'], name='idx_status'),
        ),
        migrations.AddIndex(
            model_name='onlinepaymentsmodel',
            index=models.Index(fields=['payment_datetime'], name='idx_payment_datetime'),
        ),
    ]
