# Generated by Django 5.0.4 on 2025-09-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0008_alter_cart_price_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cart',
            name='discount_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderlinesmodel',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderlinesmodel',
            name='discount_price',
            field=models.FloatField(default=0.0),
        ),
    ]
