# Generated by Django 5.0.4 on 2025-09-30 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0009_cart_discount_cart_discount_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='advance_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='balance_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
