# Generated by Django 5.0.4 on 2025-10-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0010_inventory_discount_ordermodel_advance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='discount_price',
            field=models.FloatField(default=0.0),
        ),
    ]
