# Generated by Django 5.0.4 on 2025-10-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0012_ordermodel_sales_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='paid_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
