# Generated by Django 5.0.4 on 2025-10-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0013_ordermodel_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='pending', max_length=100),
        ),
    ]
