# Generated by Django 5.0.4 on 2025-10-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0014_alter_ordermodel_order_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pagemodel',
            name='idx_description',
        ),
    ]
