# Generated by Django 5.0.4 on 2025-10-07 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0015_remove_pagemodel_idx_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepaymentsmodel',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='onlinepaymentsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinepaymentsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
