# Generated by Django 5.0.4 on 2025-10-10 13:00

import tinymce_4.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0016_onlinepaymentsmodel_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_description',
            field=tinymce_4.fields.TinyMCEModelField(blank=True, null=True),
        ),
    ]
