# Generated by Django 5.0.4 on 2025-10-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0017_ordermodel_is_downloaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepaymentsmodel',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
