# Generated by Django 5.0.4 on 2025-10-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0018_onlinepaymentsmodel_payment_mode_ordermodel_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='limited_stock',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='out_of_stock',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='warranty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
