# Generated by Django 5.0.4 on 2025-10-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0019_alter_productmodel_limited_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
