# Generated by Django 5.0.4 on 2025-10-16 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0020_alter_productmodel_short_description'),
        ('user_app', '0009_alter_contactusmodel_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('full_path', models.CharField(blank=True, max_length=100, null=True)),
                ('component', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='idx_feature_name'), models.Index(fields=['path'], name='idx_feature_path')],
            },
        ),
        migrations.CreateModel(
            name='FeatureApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_viewed', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_write', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('sequence_no', models.IntegerField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_feature_permissions', to='user_app.rolemodel')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.featuremodel')),
            ],
            options={
                'indexes': [models.Index(fields=['role'], name='idx_feature_role'), models.Index(fields=['is_viewed'], name='idx_feature_is_viewed'), models.Index(fields=['is_read'], name='idx_feature_read'), models.Index(fields=['is_write'], name='idx_feature_write'), models.Index(fields=['is_delete'], name='idx_feature_delete')],
            },
        ),
    ]
