# Generated by Django 5.0.4 on 2025-10-16 11:13

import django.db.models.deletion
import tinymce_4.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0021_featuremodel_featureapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='management_app.categorymodel')),
            ],
            options={
                'indexes': [models.Index(fields=['language_code'], name='idx_category_translation')],
                'unique_together': {('category', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='HomeCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('home_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='management_app.homecategorymodel')),
            ],
            options={
                'indexes': [models.Index(fields=['language_code'], name='idx_home_category_translation')],
                'unique_together': {('home_category', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='management_app.pagemodel')),
            ],
            options={
                'indexes': [models.Index(fields=['language_code'], name='idx_page_translation_lang')],
                'unique_together': {('page', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('feature', models.CharField(blank=True, max_length=255, null=True)),
                ('description', tinymce_4.fields.TinyMCEModelField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='management_app.productmodel')),
            ],
            options={
                'indexes': [models.Index(fields=['language_code'], name='idx_product_translation')],
                'unique_together': {('product', 'language_code')},
            },
        ),
    ]
