# Generated by Django 5.0.4 on 2025-10-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0022_categorytranslation_homecategorytranslation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
