# Generated by Django 5.0.4 on 2025-10-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0023_alter_ordermodel_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='warehouse_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
