# Generated by Django 5.0.4 on 2025-10-28 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0024_productmodel_warehouse_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='management_app.client')),
            ],
            options={
                'verbose_name': 'Client Translation',
                'verbose_name_plural': 'Client Translations',
                'unique_together': {('client', 'language_code')},
            },
        ),
    ]
