# Generated by Django 5.0.4 on 2025-11-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0025_clienttranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
