# Generated by Django 5.0.4 on 2025-11-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0026_alter_productmodel_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
    ]
