# Generated by Django 5.0.4 on 2025-12-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0027_ordermodel_discount_ordermodel_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Purchase Price'),
        ),
    ]
