# Generated by Django 5.0.4 on 2025-12-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0028_productmodel_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='transport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
