# Generated by Django 5.0.4 on 2025-12-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0029_contactmodel_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='final_total',
            field=models.FloatField(default=0.0),
        ),
    ]
