# Generated by Django 5.0.4 on 2025-12-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0030_purchaseorder_discount_purchaseorder_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_type',
            field=models.CharField(blank=True, choices=[('Urgent', 'Urgent'), ('Regular', 'Regular'), ('Normal', 'Normal')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('cod', 'cod'), ('online', 'online'), ('paid', 'paid'), ('unpaid', 'unpaid'), ('half-paid', 'half-paid'), ('credit', 'credit')], max_length=200, null=True),
        ),
    ]
