# Generated by Django 5.0.4 on 2025-09-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Retailer', 'Retailer'), ('Distributer', 'Distributer')], max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='rolemodel',
            index=models.Index(fields=['type'], name='idx_role_type'),
        ),
    ]
