# Generated by Django 5.0.4 on 2025-09-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_rolemodel_type_rolemodel_idx_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='firm_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler'), ('Distributer', 'Distributer')], max_length=100, null=True),
        ),
    ]
