# Generated by Django 5.0.4 on 2025-09-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_usermodel_firm_name_alter_rolemodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'visitor',
                'verbose_name_plural': 'visitors',
                'indexes': [models.Index(fields=['visitor_id'], name='idx_visitor_id')],
            },
        ),
    ]
