# Generated by Django 5.0.4 on 2025-09-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_visitormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='fcity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.citiesmodel'),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='fcountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.countrymodel'),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='fstate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.statesmodel'),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='postal code'),
        ),
    ]
