# Generated by Django 5.0.4 on 2025-09-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_addressmodel_fcity_addressmodel_fcountry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler'), ('Distributer', 'Distributer'), ('Employee', 'Employee')], max_length=100, null=True),
        ),
    ]
