# Generated by Django 5.0.4 on 2025-10-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_rolemodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='advance_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='unpaid_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
