# Generated by Django 5.0.4 on 2025-10-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_contactusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
