# Generated by Django 5.0.4 on 2025-10-16 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_alter_contactusmodel_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('android', 'android'), ('ios', 'ios'), ('web', 'web'), ('desktop', 'desktop'), ('other', 'other')], default='android', max_length=10)),
                ('user_id', models.CharField(max_length=10, verbose_name='User ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(default='Unknown Device', max_length=255)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('user_id', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
