# Generated by Django 5.0.4 on 2025-10-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_fcmtokenmodel_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
